spring:
  application:
    name: spring-cloud-config
  profiles:
    active: native
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz # by date
      max-file-size: 10MB # by size
server:
  port: 8888
