FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD target/faculty-1.0.jar /faculty.jar
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /faculty.jar" ]
